### ISSUE TITLE
Allow running with out a detected change

### ISSUE THREAD

**Issue by ctron** [helm/chart-testing-action#12]
Currently it is not possible run without a change being detected:

https://github.com/helm/chart-testing-action/blob/b24a1cc0eb061c27cf9409308db22b2c82b3c359/ct.sh#L40-L43

I think it would make sense allowing to also run in a case where there is no "change detection" possible. e.g. you run CI job A, which creates a new helm package, and passes it over to job B which should validate it.

**Comment by giorgiosironi** [comment]
I tried passing `lint --all` as `command`, but there are assumptions that [it is a single word](https://github.com/helm/chart-testing-action/blob/master/ct.sh#L50) so that doesn't work.

**Comment by unguiculus** [comment]
You can configure `ct` to test specific charts using the `--charts` flag. With this action, you have to use a config file to set this.

See:
* https://github.com/helm/chart-testing/blob/master/doc/ct_install.md#options
* https://github.com/helm/chart-testing-action#inputs

**Comment by cep21** [comment]
Hi,

It's unclear from the last comment how to Allow running with out a detected change.  Did https://github.com/ctron/chart-testing-action/commit/e2ef491ae60a117fcd8ee7f3df18e20c9a0ce762 get merged?  Is there an example file that will work?

**Comment by IanMoroney** [comment]
@cep21 , coming back to your comment, the documentation specifies:

```
--charts strings                 Specific charts to test. Disables changed charts detection and
                                       version increment checking. May be specified multiple times
                                       or separate values with commas
```
