### ISSUE TITLE
Version 2.5.0?

### ISSUE THREAD

**Issue by abdolence** [helm/chart-testing-action#126]
Hello,

The example says version `helm/chart-testing-action@v2.5.0` and it fails since the latest available says 2.4.0.
Was 2.5.0 forgotten to publish?

Thanks

**Comment by gaby** [comment]
Any updates on this?

**Comment by gamunu** [comment]
Use main branch for the latest release, Looks like the project is abandoned
```
- name: chart-testing setup
   uses: helm/chart-testing-action@main
```

**Comment by gaby** [comment]
@gamunu There's several people still merging stuff, but yeah using `main` may be the way to go

**Comment by cpanato** [comment]
https://github.com/helm/chart-testing-action/releases/tag/v2.5.0
