### ISSUE TITLE
Allow to output the names of changed Chart if the action run successfully

### ISSUE THREAD

**Issue by chrisduong** [helm/chart-testing-action#16]
When we have the names of changed Chart, we can use them so that we know which Chart we can publish to the registry.

Right now, I have to add an Step (install the **ct** binary) to run `list-changed` to know the chart to publish later.

**Comment by scottrigby** [comment]
Have you tried https://github.com/helm/chart-releaser-action?

**Comment by scottrigby** [comment]
Closing this due to no reply
