### ISSUE TITLE
Action is incompatible with `actions/checkout@v2`

### ISSUE THREAD

**Issue by ctron** [helm/chart-testing-action#20]
We are using the action to validate helm charts, see https://github.com/eclipse/packages/blob/master/.github/workflows/ci.yaml

However, without having knowingly changed anything, linting fails with no indication at all:

https://github.com/eclipse/packages/pull/73/checks?check_run_id=495784296

~~~
Digest: sha256:7b99d26b07eb41c19186ef5f7ac334b93736b767d971fb46976c36908440ef82
Status: Downloaded newer image for quay.io/helmpack/chart-testing:v2.4.0
e489b009fa2bfef8965b2e38b58b153ec45b6507ad3b5071de052103886c0c96

Removing ct container...
Done!
~~~

![image](https://user-images.githubusercontent.com/202474/76538698-ff980b00-647f-11ea-8637-739e1699cd4c.png)

As this is not the only PR which suffers from this, I don't think it is related to the PR. Also running `helm lint` locally works just fine.

Affected PRs:
* https://github.com/eclipse/packages/pull/66
* https://github.com/eclipse/packages/pull/73

**Comment by naseemkullah** [comment]
Try actions/checkout@v1 instead of actions/checkout@v2, it seemed to have worked in my case, would be curious if it works for you as well!

https://github.com/jaegertracing/helm-charts/pull/75#issuecomment-598515050

**Comment by ctron** [comment]
> Try actions/checkout@v1 instead of actions/checkout@v2, it seemed to have worked in my case, would be curious if it works for you as well!
> 
> [jaegertracing/helm-charts#75 (comment)](https://github.com/jaegertracing/helm-charts/pull/75#issuecomment-598515050)

Thank you! This indeed fixed the issue for us. I re-titled this issue to correctly reflect the problem.

**Comment by unguiculus** [comment]
`actions/checkout@v2` does a shallow clone by default. This can be reconfigured:

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: "0"
```

**Comment by unguiculus** [comment]
Actually, this still doesn't seem to cut it. The following is working:

```yaml
- name: Checkout
  uses: actions/checkout@v2

- name: Fetch history
  run: git fetch --prune --unshallow
```
