### ISSUE TITLE
Using --set at install time for a given chart ?

### ISSUE THREAD

**Issue by eddycharly** [helm/chart-testing-action#34]
Is this possible to specify values when installing a given chart with `ct` (using `--set` or `--values`) ?

I have a chart that needs to `--set customResourceDefinitions.create=false` when installed with `helm`v3.

Thanks

**Comment by bkimbrough88** [comment]
I thought that you could do this by passing the `--set` option to the `helm-extra-args` setting in your config file. However the linter still fails saying that the chart is missing the required values.

```
helm-extra-args: >-
  --set component=foo
  --set global.application=fee
  --set global.dockerRepo=fi
  --set global.environment=fo
  --set global.version=fum
```

I can see that the action is respecting my config:
```
HelmExtraArgs: --set component=foo --set global.application=fee --set global.dockerRepo=fi --set global.environment=fo --set global.version=fum
```

However when this runs the lint command, it is still failing to find these variables and fails validation:
```
==> Linting charts/webservice
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/deployment.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 9: found character that cannot start any token
[ERROR] templates/service.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 8: found character that cannot start any token

engine.go:159: [INFO] Missing required value: global.application must be defined
engine.go:159: [INFO] Missing required value: component must be defined
engine.go:159: [INFO] Missing required value: global.dockerRepo must be defined
engine.go:159: [INFO] Missing required value: global.environment must be defined
engine.go:159: [INFO] Missing required value: global.version must be defined
Error: Error linting charts: Error processing charts
Error: 1 chart(s) linted, 1 chart(s) failed
```

I get the same error if I do not set these values for the linter when running `helm lint` locally, but they don't appear to be used.

**Comment by bkimbrough88** [comment]
After doing more digging I found that the solution here is to use a `*-values.yaml` file in the ci directory of my chart and the linter will respect those values. See https://github.com/helm/chart-testing/issues/161#issuecomment-641493137

**Comment by unguiculus** [comment]
Closing this now. Using values files in the ci folder is the correct solution.
