### ISSUE TITLE
Missing v1.0.0 tag for action

### ISSUE THREAD

**Issue by hairmare** [helm/chart-testing-action#40]
I'm not sure if this is a bug or the omission is on purpose but the repo is missing a `v1.0.0` tag for the recent v3.0.0 release of chart-testing that was merged in #38 and documented in #39.

> ##[error]An action could not be found at the URI 'https://api.github.com/repos/helm/chart-testing-action/tarball/v1.0.0'

**Comment by unguiculus** [comment]
We're working on that. We should be able to cut a release soon.

**Comment by hairmare** [comment]
OK, thanks for the feedback
