### ISSUE TITLE
How to add private repo for dependencies 

### ISSUE THREAD

**Issue by jbuettnerbild** [helm/chart-testing-action#48]
Hi,

in my charts i have dependencies to private repositories. I've tried a lot, but couldn't find a way to set up access for helm to download the defined dependencies during the helm lint command. 
Is there a way through the config command or through environment variables?

Many thanks

**Comment by davidkarlsen** [comment]
You can configure them in the config-file like this:
```
cat ct-config.yaml 
remote: origin
chart-dirs:
- charts
chart-repos: <--
- bitnami=https://charts.bitnami.com/bitnami
namespace: chart-testing
release-label: app.kubernetes.io/instance
```

**Comment by jbuettnerbild** [comment]
i had tried this without any success. Can you give me an example. Im not sure how to define the username and password credentials for the private repo.

**Comment by davidkarlsen** [comment]
See https://github.com/helm/chart-testing/blob/master/doc/ct_lint.md "helm-repo-extra-args"

**Comment by jbuettnerbild** [comment]
i got it
`--helm-repo-extra-args strings   Additional arguments for the 'helm repo add' command to be
                                       specified on a per-repo basis with an equals sign as delimiter
                                       (e.g. 'myrepo=--username test --password secret'). May be specified
                                       multiple times or separate values with commas`
thx
