### ISSUE TITLE
Workflow justification for "No chart changes detected" fast end

### ISSUE THREAD

**Issue by cep21** [helm/chart-testing-action#49]
Hi,

I'm unsure why "No chart changes detected" fast stop is the best workflow.  Can you talk about this more?  We put our helm charts with our service code.  Other people do that to (flux is one example: https://github.com/fluxcd/flux/tree/master/chart)

It makes sense to me to try starting and testing our helm chart on every PR.  We may only modify the helm chart version infrequently, but we would want to know on each PR if the code will break the helm chart.  I imagine this would be the desired workflow for most people.  I'm maybe misunderstanding something about why this would be undesired or not want to be the default.

I imagine this is related to https://github.com/helm/chart-testing-action/issues/12

**Comment by cpanato** [comment]
this is explained here https://github.com/helm/chart-testing-action/issues/12#issuecomment-602057058
