### ISSUE TITLE
yamllint not reporting line numbers

### ISSUE THREAD

**Issue by IanMoroney** [helm/chart-testing-action#70]
I noticed that `ct lint` calls yamllint to validate Chart.yaml, but when it spots a warning or an error, it doesn't tell you which line it is:
```
>>> yamllint --config-file /home/runner/_work/_tool/ct/v3.3.0/x86_64/etc/lintconf.yaml mychart/Chart.yaml
Error: [comments] too few spaces before comment
Error: Error linting charts: Error processing charts
```

Conversely, yamllint itself in its default configuration reports the line number:

```
yamllint b2c-perf-test-client/Chart.yaml 
b2c-perf-test-client/Chart.yaml
  1:1       warning  missing document start "---"  (document-start)
  26:14     warning  too few spaces before comment  (comments)
```

Either:
How do we get `ct lint` to report line numbers,
or
Can you configure lintconf.yaml to report line numbers by default ?

Additionally, it may be the case where your lintconf.yaml is reporting warnings as errors, as yamllint 1.26.1 only reported the comment issue as a `warning` and not an `error`.

**Comment by tylerauerbeck** [comment]
@IanMoroney This may get more responses by creating over in the main ct repo: https://github.com/helm/chart-testing

**Comment by gcaracuel** [comment]
This issues seems a clone of https://github.com/helm/chart-testing-action/issues/67

**Comment by Rotonen** [comment]
The line numbers missing is an artefact of  the `auto` output format picking up it is running in a Github Action and that output format not having the file names or line numbers on there. A design decision of `yamllint` itself.

https://github.com/adrienverge/yamllint/blob/85ccd625a382423edd988fcb796c4dd5897886fb/yamllint/cli.py#L112-L114

Forcing the output format of `yamllint` to `standard` would get you the output you seek.

**Comment by cpanato** [comment]
closing as inactive
