### ISSUE TITLE
Add action to GitHub marketplace

### ISSUE THREAD

**Issue by scottrigby** [helm/chart-testing-action#9]
## Current status

Action unique name still not released after deletion - details in https://github.com/helm/chart-testing-action/issues/9#issuecomment-563012746. I submitted a GitHub support request.

 ## Original issue
~Currently waiting to hear back from @Flydiverny about changing the name of https://github.com/marketplace/actions/helm-chart-testing (currently linked to https://github.com/Flydiverny/chart-testing-action) so https://github.com/helm/chart-testing-action can use the canonical name `helm-chart-testing`.~

<img width="766" alt="Screen Shot 2019-12-08 at 6 26 47 PM" src="https://user-images.githubusercontent.com/407675/70398343-6670d880-19e8-11ea-9782-65a81a5303a1.png">

**Comment by scottrigby** [comment]
@Flydiverny Thanks for working on this! 

So far, de-listed the action, deleted the releases associated with the marketplace action, and archived the git repo (with a link to this one - https://github.com/Flydiverny/chart-testing-action/commit/24f95944ab7d5ad4a17fd9fa6cfc16baa90ac57c)

But I can't create a marketplace release yet. Perhaps we wait for eventual consistency in GitHub marketplace tooling, or if that doesn't work we should submit a help request.

**Comment by Flydiverny** [comment]
💃

**Comment by scottrigby** [comment]
Action unique name still not released after deletion. I submitted a support request.

**Comment by scottrigby** [comment]
Done. Thanks everyone 🙌 https://github.com/marketplace/actions/helm-chart-testing
