### ISSUE TITLE
empty response

### ISSUE THREAD

**Issue by denispeyrusaubes** [helm/chart-testing-action#97]
Hi,

following command always return empty result, whereas I did some some changes to my chart :

> this command is run when I am in the 'develop' branch

```
$ ct list-changed --config .github/ct-config.yaml --target-branch main
charts/mychartfoldername
```

any help appreciated !

D.

**Comment by cpanato** [comment]
looking at your code snippet looks like that return the chart that has a change and not an empty response 
will close this issue, but feel free to reopen or open a new one
